name: Notify when a new '/packages/**/node_modules' directory appears

on:
  push:
    paths:
      - '**/package*.json'

jobs:
  count-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '/.nvmrc'

      - name: Count packages
        id: s1
        run: |2
          echo "packages_count=$(find packages -mindepth 1 -maxdepth 1 -type d | wc -l | tr -d '[:space:]')" >> "$GITHUB_OUTPUT"
    outputs:
      packages_count: ${{steps.s1.outputs.packages_count}}

  notify:
    needs:
      - count-packages
    if: needs.count-packages.outputs.packages_count > 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci

      - name: Find nested 'node_modules' dirs
        run: |2
          directories=$(find packages -type d -name 'node_modules' | tr -d '[:space:]')

          if [ -n "$directories" ]; then
            echo ⛔️ "Error: Found nested 'node_modules' directories:"
            echo $directories
            exit 1
          else
            echo ✅ "No nested 'node_modules' directories found."
          fi
