name: Test change

on:
  push:
    paths:
      - 'packages/**'
      - '.eslintrc.base.cjs'
      - 'tsconfig.json'

      - 'package-lock.json'
      - 'package.json'

      - '.github/workflows/**'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '/.nvmrc'

      - name: Run audit
        run: npm audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '/.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lint all source files
        run: npm run lint -ws --if-present

  build:
    runs-on: ubuntu-latest
    needs:
      - audit
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '/.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build all workspaces
        run: npm run build -ws

  test:
    needs:
      - build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '/.nvmrc'

      - name: Install dependencies
        run: npm ci

      # see https://github.com/vitejs/vite/discussions/15532
      - if: matrix.os == 'ubuntu-latest'
        name: Fix missing Linux-specific dependency issue
        run: npm i -ws --no-save @rollup/rollup-linux-x64-gnu

      # see https://github.com/vitejs/vite/discussions/15532
      - if: matrix.os == 'windows-latest'
        name: Fix missing Windows-specific dependency issue
        run: npm i -ws --no-save @rollup/rollup-win32-x64-msvc

      - name: Test on ${{ matrix.os }}
        run: npm test -ws
